### ISSUE TITLE
Cannot start debug mode

### ISSUE THREAD

**Issue by luckylooke** [lebesnec/island.js#2]
I am setting config.allowDebug to TRUE, but nothing changed on output. :/

**Comment by lebesnec** [comment]
you have to click on the map to enter "debug" mode

**Comment by lebesnec** [comment]
Also, this can only be set at the initialisation : 

    Island.init({
        allowDebug:true
    });

It can take a few seconds to show up after you click if you have a lot of sites.

**Comment by luckylooke** [comment]
Ok.. I will try it in the evening and let you know. It will be in few
hours. ;-)

**Comment by luckylooke** [comment]
I am sorry that I missed click binding in index.html, debuging mode works now perfectly.

Btw I have refactored your code a bit to get Phaser.io plugin. So I have mostly changed render functions and I also have added possibility to seed the island. So if you provide same seed on init, you get same pseudo-random island. I am also making some simple demo game for it to show its possibilities. I hope I will publish it soon. 

Thank you for your great work I can build on. ;)

**Comment by lebesnec** [comment]
This is mostly a port From Amit algorithm (http://www-cs-students.stanford.edu/~amitp/game-programming/polygon-map-generation/), he wiil be happy to heard about this :)
I look forward for your demo !

**Comment by luckylooke** [comment]
I knew that, I was studing his blog and then found link to your port in comments ;)
As first step I have published the plugin here: http://luckylooke.github.io/phaser-islandjs-plugin/
I will be working on demo game and publish it as next step.

**Comment by rangent** [comment]
@luckylooke looks great!
