### ISSUE TITLE
Question: How do you make it seed-based so it is the same every time with the same seed?

### ISSUE THREAD

**Issue by AndrewMast** [lebesnec/island.js#4]
How do you make it seed-based so it is the same every time with the same seed?

I have tried to use [seedrandom.min.js](https://github.com/davidbau/seedrandom) and add `Math.seedrandom(this.seed);` It works, but when I resize the canvas, it changes.

EDIT: I tried out the fork made by @ToddAT but it still changes when the canvas size does.

**Comment by amitp** [comment]
I don't know the answer to your question but I'm curious — are you using the random point distribution or the grid distribution?

**Comment by AndrewMast** [comment]
I am using `sitesDistribution: 'hexagon'`

**Comment by AndrewMast** [comment]
Basically, I don't want anything "random".

**Comment by lebesnec** [comment]
If you set a new width and height in the config, the size of the perlin canvas will be resized to 1/3 of the island canvas. Try setting perlinWidth and perlinHeight to a fixed value.

**Comment by AndrewMast** [comment]
Nope. Still changes.

**Comment by lebesnec** [comment]
Try setting sitesRandomisation and nbGraphRelaxation to 0 in the initial config.

This fork is seed based so you may want to look at it : http://luckylooke.github.io/phaser-islandjs-plugin/

**Comment by AndrewMast** [comment]
That works! Thanks.
